nginx_nodes:
  hosts:
    nginx01:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/nginx01/virtualbox/private_key
  vars:
    alt_http_port: 8080    
    ansible_host: 127.0.0.1
    ansible_user: vagrant
