- name: Install needed packages
  ansible.builtin.package:
    name: 
      - nginx
    state: present

- name: Deploy nginx config
  ansible.builtin.template:
    dest: /etc/nginx/sites-available/default
    mode: '644'
    owner: root
    src: nginx.default.j2
  notify:
    - Nginx restart

